apiVersion: v1
kind: Service
metadata:
  name: wisecow-service
spec:
  selector:
    app: wisecow
  ports:
    - protocol: TCP
      port: 80  # Port exposed by the service inside the cluster
      targetPort: 4499  # The port inside the container
      nodePort: 30080  # The port on the node (host machine)
  type: NodePort  # Use NodePort for local access
