apiVersion: v1
kind: Service
metadata:
  name: wisecow-service
spec:
  selector:
    app: wisecow
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 4499            # Service port inside the cluster
      targetPort: 4499      # Matches containerPort in your deployment
      nodePort: 30080       # Port exposed on localhost
