name: Build and Deploy Wisecow Application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/wisecow:latest

  deploy:
    runs-on: self-hosted  # Runs on your local machine where kind is running
    needs: build
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Apply Kubernetes Manifests
        run: |
          kubectl apply -f kubernetes/manifests/deployment.yaml
          kubectl apply -f kubernetes/manifests/service.yaml

      - name: Update Deployment Image
        run: |
          kubectl set image deployment/wisecow wisecow=${{ secrets.DOCKER_USERNAME }}/wisecow:latest
          kubectl rollout restart deployment/wisecow

      - name: Wait for Deployment to Stabilize
        run: kubectl rollout status deployment/wisecow

      - name: Get Pod Status
        run: kubectl get pods
